# -*- coding: utf-8 -*-
from odoo import api, fields, models, _
from odoo.exceptions import UserError, ValidationError


class TaskTracker(models.Model):
    """
    Task Tracker — Main model.
    Generated by create-odoo-module (https://create-odoo-module.dev)
    """
    _name        = 'task.tracker'
    _description = 'Task Tracker'
    _inherit     = ['mail.thread', 'mail.activity.mixin']
    _order       = 'name asc'
    _rec_name    = 'name'

    # ── Identity ──────────────────────────────────────────────────────────────
    name = fields.Char(
        string='Name',
        required=True,
        tracking=True,
        index=True,
        copy=False,
    )
    reference = fields.Char(
        string='Reference',
        copy=False,
        readonly=True,
        default='New',
    )
    description = fields.Text(string='Description')
    active = fields.Boolean(default=True, tracking=True)
    color  = fields.Integer(string='Color')

    # ── Status ───────────────────────────────────────────────────────────────
    state = fields.Selection([
        ('draft',       'Draft'),
        ('confirmed',   'Confirmed'),
        ('in_progress', 'In Progress'),
        ('done',        'Done'),
        ('cancelled',   'Cancelled'),
    ], default='draft', tracking=True, string='Status', required=True)

    # ── Relations ─────────────────────────────────────────────────────────────
    user_id = fields.Many2one(
        'res.users',
        string='Responsible',
        default=lambda self: self.env.user,
        tracking=True,
        index=True,
    )
    company_id = fields.Many2one(
        'res.company',
        string='Company',
        default=lambda self: self.env.company,
        required=True,
        index=True,
    )
    tag_ids = fields.Many2many(
        'res.partner.category',
        string='Tags',
    )

    # ── Dates ────────────────────────────────────────────────────────────────
    date_start  = fields.Date(string='Start Date')
    date_end    = fields.Date(string='End Date')
    create_date = fields.Datetime(readonly=True)
    write_date  = fields.Datetime(readonly=True)

    # ── Priority / KPIs ───────────────────────────────────────────────────────
    priority = fields.Selection([
        ('0', 'Normal'),
        ('1', 'Low'),
        ('2', 'High'),
        ('3', 'Very High'),
    ], default='0', string='Priority')

    # ── Computed ─────────────────────────────────────────────────────────────
    display_name = fields.Char(compute='_compute_display_name', store=True)
    duration_days = fields.Integer(compute='_compute_duration', store=True, string='Duration (Days)')

    @api.depends('name', 'reference', 'state')
    def _compute_display_name(self):
        for rec in self:
            ref = rec.reference if rec.reference != 'New' else ''
            rec.display_name = f"[{rec.state.upper()}] {rec.name}" + (f" ({ref})" if ref else '')

    @api.depends('date_start', 'date_end')
    def _compute_duration(self):
        for rec in self:
            if rec.date_start and rec.date_end:
                rec.duration_days = (rec.date_end - rec.date_start).days
            else:
                rec.duration_days = 0

    # ── Constraints ───────────────────────────────────────────────────────────
    @api.constrains('date_start', 'date_end')
    def _check_dates(self):
        for rec in self:
            if rec.date_start and rec.date_end and rec.date_start > rec.date_end:
                raise ValidationError(_('Start date must be before end date.'))

    _sql_constraints = [
        ('reference_unique', 'UNIQUE(reference, company_id)',
         'Reference must be unique per company.'),
    ]

    # ── Sequence ──────────────────────────────────────────────────────────────
    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            if vals.get('reference', 'New') == 'New':
                vals['reference'] = self.env['ir.sequence'].next_by_code('task.tracker') or 'New'
        return super().create(vals_list)

    # ── Business Logic ────────────────────────────────────────────────────────
    def action_confirm(self):
        for rec in self:
            if rec.state != 'draft':
                raise UserError(_('Only draft records can be confirmed.'))
        self.write({'state': 'confirmed'})

    def action_start(self):
        self.filtered(lambda r: r.state == 'confirmed').write({'state': 'in_progress'})

    def action_done(self):
        self.write({'state': 'done'})

    def action_cancel(self):
        if any(r.state == 'done' for r in self):
            raise UserError(_('Cannot cancel a completed record.'))
        self.write({'state': 'cancelled'})

    def action_reset_draft(self):
        self.write({'state': 'draft'})

    # ── Smart button actions ───────────────────────────────────────────────────
    def action_open_form(self):
        self.ensure_one()
        return {
            'type': 'ir.actions.act_window',
            'res_model': self._name,
            'res_id': self.id,
            'view_mode': 'form',
            'target': 'current',
        }
