# -*- coding: utf-8 -*-
{
    'name': 'Task Tracker',
    'version': '17.0.1.0.0',
    'category': 'Project',
    'summary': 'Auto-generated by create-odoo-module CLI',
    'description': """
        Task Tracker Module
        ===================
        Full-stack Odoo module with CRUD + REST API.
        Generated by create-odoo-module — https://create-odoo-module.dev
    """,
    'author': 'Example Corp',
    'website': 'https://yourcompany.com',
    'depends': ['base', 'mail', 'web', 'project'],
    'data': [
        'security/ir.model.access.csv',
        'security/task_tracker_security.xml',
        'views/task_tracker_views.xml',
        'views/task_tracker_menus.xml',
        'data/task_tracker_data.xml',
        'report/task_tracker_report.xml',
        'report/task_tracker_report_template.xml',
        'wizard/task_tracker_wizard_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'task_tracker/static/src/js/task_tracker.js',
            'task_tracker/static/src/scss/task_tracker.scss',
        ],
    },
    'demo': [],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
