# ═══════════════════════════════════════════════════════════════════════════
# Task Tracker — Deploy Script (Windows PowerShell)
# Generated by create-odoo-module — https://create-odoo-module.dev
# ═══════════════════════════════════════════════════════════════════════════
#Requires -Version 5.1
$ErrorActionPreference = "Stop"

# ── Load environment ────────────────────────────────────────────────────────
if (Test-Path ".env") {
    Get-Content ".env" | ForEach-Object {
        if ($_ -match "^([^#=]+)=(.*)$") {
            [System.Environment]::SetEnvironmentVariable($Matches[1].Trim(), $Matches[2].Trim(), "Process")
        }
    }
} else {
    Write-Host "⚠  .env file not found. Copy .env.example to .env and fill in your credentials." -ForegroundColor Yellow
    exit 1
}

$MODULE_NAME  = "task_tracker"
$ODOO_URL     = $env:ODOO_URL     ?? "http://localhost:8069"
$ODOO_DB      = $env:ODOO_DB      ?? "odoo"
$ODOO_USER    = $env:ODOO_USER    ?? "admin"
$ODOO_PASSWORD = $env:ODOO_PASSWORD ?? "admin"
$ADDONS_PATH  = $env:ODOO_ADDONS_PATH ?? "C:\odoo\custom-addons"

Write-Host "`n  Deploying $MODULE_NAME → $ODOO_URL`n" -ForegroundColor Cyan

# ── Step 1: Validate source ──────────────────────────────────────────────────
if (-not (Test-Path "odoo_module")) {
    Write-Host "  ✗  odoo_module/ directory not found." -ForegroundColor Red
    exit 1
}
Write-Host "  ✔  Source: odoo_module/" -ForegroundColor Green

# ── Step 2: Copy module ──────────────────────────────────────────────────────
$DEST = Join-Path $ADDONS_PATH $MODULE_NAME
New-Item -ItemType Directory -Force -Path $DEST | Out-Null
Copy-Item -Path "odoo_module\*" -Destination $DEST -Recurse -Force
Write-Host "  ✔  Copied to $DEST" -ForegroundColor Green

# ── Step 3: Install/upgrade via XML-RPC ─────────────────────────────────────
Write-Host "  ℹ  Triggering install/upgrade via XML-RPC..." -ForegroundColor Cyan

$pyScript = @"
import xmlrpc.client, sys
url = '$ODOO_URL'; db = '$ODOO_DB'; user = '$ODOO_USER'; password = '$ODOO_PASSWORD'; module = '$MODULE_NAME'
common = xmlrpc.client.ServerProxy(f'{url}/xmlrpc/2/common')
uid = common.authenticate(db, user, password, {})
if not uid:
    print('Invalid credentials'); sys.exit(1)
models = xmlrpc.client.ServerProxy(f'{url}/xmlrpc/2/object')
installed = models.execute_kw(db, uid, password, 'ir.module.module', 'search',
    [[['name','=',module],['state','in',['installed','to upgrade']]]])
if installed:
    models.execute_kw(db, uid, password, 'ir.module.module', 'button_immediate_upgrade', [installed])
    print(f'Module upgraded: {module}')
else:
    to_install = models.execute_kw(db, uid, password, 'ir.module.module', 'search',
        [[['name','=',module]]])
    models.execute_kw(db, uid, password, 'ir.module.module', 'button_immediate_install', [to_install])
    print(f'Module installed: {module}')
"@

python3 -c $pyScript

Write-Host "  ✔  Deploy complete!" -ForegroundColor Green
Write-Host "`n  Open: $ODOO_URL/web`n" -ForegroundColor Cyan
