#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════════════
# Task Tracker — Deploy Script (Linux / macOS)
# Generated by create-odoo-module — https://create-odoo-module.dev
# ═══════════════════════════════════════════════════════════════════════════
set -euo pipefail

# ── Load environment ────────────────────────────────────────────────────────
if [[ -f ".env" ]]; then
  set -a && source .env && set +a
else
  echo "⚠  .env file not found. Copy .env.example to .env and fill in your credentials."
  exit 1
fi

MODULE_NAME="task_tracker"
ODOO_URL="${ODOO_URL:-http://localhost:8069}"
ODOO_DB="${ODOO_DB:-odoo}"
ODOO_USER="${ODOO_USER:-admin}"
ODOO_PASSWORD="${ODOO_PASSWORD:-admin}"
ADDONS_PATH="${ODOO_ADDONS_PATH:-/opt/odoo/custom-addons}"
SERVICE="${ODOO_SERVICE:-odoo}"

# ── Colors ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; RESET='\033[0m'

info()    { echo -e "  ${CYAN}ℹ${RESET}  $1"; }
success() { echo -e "  ${GREEN}✔${RESET}  $1"; }
warn()    { echo -e "  ${YELLOW}⚠${RESET}  $1"; }
error()   { echo -e "  ${RED}✗${RESET}  $1"; exit 1; }
header()  { echo -e "\n${BOLD}${CYAN}$1${RESET}\n"; }

header "Deploying ${MODULE_NAME} → ${ODOO_URL}"

# ── Step 1: Validate source ──────────────────────────────────────────────────
if [[ ! -d "odoo_module" ]]; then
  error "odoo_module/ directory not found. Run this script from the project root."
fi
success "Source directory: odoo_module/"

# ── Step 2: Copy module to addons path ──────────────────────────────────────
DEST="${ADDONS_PATH}/${MODULE_NAME}"
info "Copying to ${DEST}..."
mkdir -p "${DEST}"
cp -r odoo_module/. "${DEST}/"
success "Module copied to ${DEST}"

# ── Step 3: Install or upgrade via XML-RPC ──────────────────────────────────
info "Triggering install/upgrade via XML-RPC..."
python3 - <<PYTHON
import xmlrpc.client, sys

url      = "${ODOO_URL}"
db       = "${ODOO_DB}"
user     = "${ODOO_USER}"
password = "${ODOO_PASSWORD}"
module   = "${MODULE_NAME}"

common = xmlrpc.client.ServerProxy(f'{url}/xmlrpc/2/common')
try:
    uid = common.authenticate(db, user, password, {})
except Exception as e:
    print(f"  ✗  Authentication failed: {e}", file=sys.stderr)
    sys.exit(1)

if not uid:
    print("  ✗  Invalid credentials", file=sys.stderr)
    sys.exit(1)

models = xmlrpc.client.ServerProxy(f'{url}/xmlrpc/2/object')

# Check if module is installed
installed = models.execute_kw(db, uid, password,
    'ir.module.module', 'search',
    [[['name', '=', module], ['state', 'in', ['installed', 'to upgrade']]]]
)

if installed:
    # Upgrade
    models.execute_kw(db, uid, password,
        'ir.module.module', 'button_immediate_upgrade', [installed]
    )
    print(f"  ✔  Module '{module}' upgraded successfully")
else:
    # Install
    to_install = models.execute_kw(db, uid, password,
        'ir.module.module', 'search',
        [[['name', '=', module]]]
    )
    if not to_install:
        print(f"  ✗  Module '{module}' not found in Odoo. Check ODOO_ADDONS_PATH.", file=sys.stderr)
        sys.exit(1)
    models.execute_kw(db, uid, password,
        'ir.module.module', 'button_immediate_install', [to_install]
    )
    print(f"  ✔  Module '{module}' installed successfully")
PYTHON

success "Deploy complete!"
echo ""
echo -e "  ${BOLD}Open:${RESET} ${ODOO_URL}/web#action=task_tracker"
echo ""
